

services:
  - type: web
    name: ifsc-finder-bot
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: false