

services:
  - type: web
    name: ifsc-finder-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python telegram_ifsc_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9