services:
  - type: web
    name: ifsc-finder-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python telegram_ifsc_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
    runtime: python-3.11.9
