

services:
  - type: web
    name: ifsc-finder-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_ifsc_bot.py
    autoDeploy: true
